spring.application.name=serviceA
server.port= 8080

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.serviceA.register-health-indicator=true
resilience4j.circuitbreaker.instances.serviceA.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.serviceA.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.serviceA.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.serviceA.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.serviceA.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.serviceA.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.serviceA.sliding-window-size=10
resilience4j.circuitbreaker.instances.serviceA.sliding-window-type=COUNT_BASED

#retry

resilience4j.retry.instances.serviceA.max-attempts=5
resilience4j.retry.instances.serviceA.waitDuration = 10s
#ratelimiter
resilience4j.ratelimiter.instances.serviceBLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.serviceBLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.serviceBLimiter.timeout-duration=2ms
